// <auto-generated />
using System;
using KorpERP.Notas.API.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KorpERP.Notas.API.Migrations
{
    [DbContext(typeof(NotasDbContext))]
    partial class NotasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KorpERP.Notas.API.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmProcessamento")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("KorpERP.Notas.API.Models.NotaFiscalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NotaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Processado")
                        .HasColumnType("boolean");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotaId");

                    b.ToTable("NotaFiscalItem");
                });

            modelBuilder.Entity("KorpERP.Notas.API.Models.NotaFiscalItemFalhou", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MotivoFalha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NotaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotaId");

                    b.ToTable("NotaFiscalItemFalhou");
                });

            modelBuilder.Entity("KorpERP.Notas.API.Models.NotaFiscalItemProcessado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NotaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Processado")
                        .HasColumnType("boolean");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotaId");

                    b.ToTable("NotaFiscalItemProcessado");
                });

            modelBuilder.Entity("KorpERP.Notas.API.Models.ProdutoProjection", b =>
                {
                    b.Property<int>("ProdutoProjectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProdutoProjectionId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Saldo")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("ProdutoProjectionId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("KorpERP.Notas.API.Models.NotaFiscalItem", b =>
                {
                    b.HasOne("KorpERP.Notas.API.Models.Nota", "Nota")
                        .WithMany("Itens")
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("KorpERP.Notas.API.Models.NotaFiscalItemFalhou", b =>
                {
                    b.HasOne("KorpERP.Notas.API.Models.Nota", "Nota")
                        .WithMany("ItensFalhados")
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("KorpERP.Notas.API.Models.NotaFiscalItemProcessado", b =>
                {
                    b.HasOne("KorpERP.Notas.API.Models.Nota", "Nota")
                        .WithMany("ItensProcessados")
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("KorpERP.Notas.API.Models.Nota", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("ItensFalhados");

                    b.Navigation("ItensProcessados");
                });
#pragma warning restore 612, 618
        }
    }
}
